export const actionTypes = {
    FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_FAILED: 'FETCH_ITEMS_FAILED',
    FETCH_MENUS_SUCCESS: 'FETCH_MENUS_SUCCESS',
    FETCH_MENUS_FAILED: 'FETCH_MENUS_FAILED'
}